Bootstrap: docker
From: continuumio/miniconda3:latest
Stage: condabuild
%files
environments/illumina/environment.yml /environment.yml
environments/extras.yml /extras.yml
%labels
authors="Matt Bull" 
description="Docker image containing all requirements for the ARTIC project's ncov2019 pipeline"
%post

/opt/conda/bin/conda install mamba -c conda-forge && \
/opt/conda/bin/mamba env create -f /environment.yml #&& \
#/opt/conda/bin/mamba env update -f /extras.yml -n artic-ncov2019-illumina


Bootstrap: docker
From: debian:buster-slim
Stage: final

%post
apt-get update
mkdir -p /usr/share/man/man1
dpkg --configure -a
apt-get install -f
apt-get install -y wget git procps r-base=3.5.2-1 libxml2-dev libssl-dev curl libcurl4-openssl-dev python2.7
apt-get clean -y
R -e 'install.packages("devtools", repos="https://cloud.r-project.org")'
R -e 'library(devtools); install_version("seqinr", version = "4.2-5", repos="https://cloud.r-project.org")'
R -e 'library(devtools); install_version("stringr", version = "1.4.0", repos="https://cloud.r-project.org")'
R -e 'library(devtools); install_version("ggplot2", version = "3.3.3", repos="https://cloud.r-project.org")'
R -e 'library(devtools); install_version("reshape", version = "0.8.8", repos="https://cloud.r-project.org")'
wget http://opengene.org/MutScan/mutscan
chmod 777 ./mutscan
mv mutscan /opt/conda/envs/artic-ncov2019-illumina/bin
export PATH=/opt/conda/envs/artic-ncov2019-illumina/bin:$PATH
apt-get install -y npm
npm install --global @neherlab/nextclade

%files from condabuild
  /opt/conda/envs/artic-ncov2019-illumina /opt/conda/envs/artic-ncov2019-illumina

%environment
export PATH=/opt/conda/envs/artic-ncov2019-illumina/bin:$PATH
export JAVA_HOME=/opt/conda/envs/artic-ncov2019-illumina
